model:
  type: "fastai"  #--- Available:  "faster_rcnn" and "fastai"

paths:
  #----- faster_rcnn
  train_data: "FASTER_RCNN_TRAINING_DATASET_PATH"
  train_annotations: "FASTER_RCNN_TRAINING_ANNOTATIONS_PATH"
  val_data: "FASTER_RCNN_VALIDATION_DATASET_PATH"
  val_annotations: "FASTER_RCNN_VALIDATION_ANNOTATIONS_PATH"
  frcnn_model_save_path: "FASTER_RCNN_MODEL_SAVE_PATH"
  frcnn_model_load_path: "FASTER_RCNN_MODEL_LOAD_PATH"
  #----- fastai
  fastai_data: "FASTAI_TRAINING_DATASET_PATH"
  fastai_model_save_path: "FASTAI_MODEL_SAVE_PATH"
  fastai_model_load_path: "FASTAI_MODEL_LOAD_PATH"

rcnn_training:
  batch_size: 4
  num_epochs: 5
  learning_rate: 0.005
  momentum: 0.9
  weight_decay: 0.0005
  num_classes: 13  #--- 12 handsigns + background
  resize: [224, 224]

fastai_training:
  learning_rate: 3e-3
  epochs: 10

labels:
  id_to_name:
    1: "bird"
    2: "boar"
    3: "dog"
    4: "dragon"
    5: "hare"
    6: "horse"
    7: "monkey"
    8: "ox"
    9: "ram"
    10: "rat"
    11: "snake"
    12: "tiger"
